### ISSUE TITLE
Missing site deployment since jQuery 1.12

### ISSUE THREAD

**Issue by andyli** [jquery/api.jquery.com#890] opened 2016-02-14 18:07 UTC
jQuery 1.12 / 2.2 has been released more than a month. Doc updates like the addition of `htmlPrefilter` and `uniqueSort` has been made to this repo, but not yet reflected in the live site of api.jquery.com.

**Comment by AurelioDeRosa** [comment] 2016-02-14 22:06
I'll create a new tag once #891 is merged. Thank you for the ping on this.

**Comment by AurelioDeRosa** [comment] 2016-02-14 23:56
@dmethvin Should I tag the new release as 1.12?

**Comment by dmethvin** [comment] 2016-02-17 22:20
@timmywil do you have a preference here?

**Comment by timmywil** [comment] 2016-02-17 23:14
I prefer 1.12.0.

**Comment by AurelioDeRosa** [comment] 2016-02-17 23:26
Cool. I'll do that! Thank you

**Comment by AurelioDeRosa** [comment] 2016-02-17 23:31
Version 1.12.0 has been released.

**Comment by AurelioDeRosa** [comment] 2016-02-19 00:02
@dmethvin I've pushed the tag but the changes are not published after 24h. Are you aware of any issue?

**Comment by dmethvin** [comment] 2016-02-22 15:35
@AurelioDeRosa it looks like this didn't push but I am not sure why.

**Comment by dmethvin** [comment] 2016-02-22 15:37
I don't see the checked-selector one either but I do see the tag. Is it in stage for you?

**Comment by AurelioDeRosa** [comment] 2016-02-22 15:38
The checked-selector doesn't have a tag associated. If you want I can release a version 1.12.1 and see if it's published. What do you think?

**Comment by dmethvin** [comment] 2016-02-22 15:38
Is either of those pushed to stage though? I don't see them in stage either

**Comment by AurelioDeRosa** [comment] 2016-02-22 15:59
Not that I can see.

**Comment by dmethvin** [comment] 2016-02-22 16:59
If there aren't any deployment errors being thrown there must be something wrong with the server then? @aulvi any ideas?

**Comment by AurelioDeRosa** [comment] 2016-02-26 22:18
I pushed another tag today and it's still not published. We definitely have an issue here.

**Comment by aulvi** [comment] 2016-02-26 22:21
@dmethvin @AurelioDeRosa Sorry I missed your ping previously. I'll take a look and update this Issue again shortly.

**Comment by aulvi** [comment] 2016-02-26 22:54
@AurelioDeRosa It appears the tag is named incorrectly, there is one too many periods.

Current: v.1.12.1
Should be: v1.12.1

Please correct the tag and try again. Assign this Issue back to me if that doesn't work, thanks!

**Comment by AurelioDeRosa** [comment] 2016-02-26 22:59
Hi @aulvi.

Don't worry and thank you for checking t his issue. It's true that the last one was incorrect and I've fixed it now. However, the website didn't build even with the previous correct tag (1.12.0).

**Comment by aulvi** [comment] 2016-02-26 23:04
@AurelioDeRosa Cool, thanks for fixing the tag. The first step of the process is pulling the updated code, so now I can advance and find the next failing step. I'll update again shortly, thanks!

**Comment by aulvi** [comment] 2016-02-26 23:12
@AurelioDeRosa The grunt tasks completed successfully. How can I easily verify that the api site has been updated?

**Comment by AurelioDeRosa** [comment] 2016-02-26 23:16
You should find a text that reads:

> jQuery doesn't officially support SVG. Using jQuery methods on SVG documents, unless explicitly documented for that method, might cause unexpected behaviors.

in the [find()](https://api.jquery.com/find/) and [removeAttr()](https://api.jquery.com/removeAttr/) pages.

**Comment by aulvi** [comment] 2016-02-26 23:55
I've dug into this problem a bit and have no quick solution. All the scripts are reporting back happily, but the content we're creating for WP isn't making it into WP.

My best guess is that there's a stale node module somewhere, but it's going to take a bit of probing to find it. I'll update again when I know more, sorry this is moving slowly.

**Comment by aulvi** [comment] 2016-02-27 01:43
When `grunt deploy` runs, it's node process eats up a bunch of memory and is killed. I tried increasing the memory limit with no success. Below is the last bit of output when running in verbose mode:

```
Running "wordpress-validate" task
Verifying XML-RPC version...
XML-RPC version matches Node.js version.
Validated 94 terms.
Validated 314 posts.

Running "wordpress-sync" task
Synchronizing terms...
Getting taxonomies from WordPress...
Got taxonomies from WordPress.
Getting category terms...
Got category terms.
Getting post_tag terms...
Got post_tag terms.
Getting post_format terms...
Got post_format terms.
Publishing terms...
Publishing category terms...
Editing category ajax...
Edited category ajax.
Editing category global-ajax-event-handlers...
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
```

Still digging.

**Comment by dmethvin** [comment] 2016-02-27 02:11
Hmm, I wonder if some recent change brought out this bug. There were some changes made to the global ajax event pages and also the grunt-jquery-content plugin back in December. Do we have a log of the most recent successful deployments?

**Comment by dmethvin** [comment] 2016-02-27 02:12
Oh also @AurelioDeRosa have you done an `npm install` since the grunt-jquery-content dependency was updated in December?

**Comment by aulvi** [comment] 2016-02-27 02:41
@dmethvin I've removed and re-populated `node_modules` a few times but no change in behavior.

Each time the task fails, it's during the `global-ajax-event-handlers` category. You mentioned that changes were made to those pages, was anything new done in the markup (or whatever?)

We have basic logging, to a point, when the deployment is initiated. I do not believe we have enough granularity in the logging to know when the last mile worked successfully (ie, pushing the change into Wordpress). Everything else, up to that point, appears to be correct.

**Comment by AurelioDeRosa** [comment] 2016-02-27 11:09
No, I haven't updated the module @dmethvin.

**Comment by kswedberg** [comment] 2016-02-27 15:21
@aulvi : For what it's worth, I haven't been able to `grunt deploy` locally for at least a couple months now. @scottgonzalez , could the problem with the production deployment process be the same as the problem on my machine that I mentioned to you a while back?

**Comment by scottgonzalez** [comment] 2016-02-29 14:36
I'm pretty sure this has been broken for two and half months, since I implemented a fix for WordPress 4.4's `null` handling in https://github.com/scottgonzalez/node-wordpress/commit/3f844fc3f21be1cbba5b9780133013bd9b2c1117 and https://github.com/scottgonzalez/gilded-wordpress/commit/e8e71e7fb35671670fcf271d5cf497303ff284fc. At the same time, I upgraded the xmlrpc module in https://github.com/scottgonzalez/node-wordpress/commit/014f4541fc72953570c2c3f3f3d25b82f3f42347.

I haven't debugged the issue and don't remember if there was another site that failed to deploy (it was either just this site or one more).

**Comment by dmethvin** [comment] 2016-02-29 16:39
Is it possible to downgrade the xmlrpc module and see if it fixes things? That seems the likely suspect.

**Comment by scottgonzalez** [comment] 2016-02-29 16:58
Sure. I'd recommend testing it locally rather than going through a many project deploy process just to test.

**Comment by mgol** [comment] 2016-03-08 20:01
> @AurelioDeRosa It appears the tag is named incorrectly, there is one too many periods.
> 
> Current: v.1.12.1
> Should be: v1.12.1

FWIW, it's best to not create tags manually but to run `npm version patch` (or `minor`, or `major` instead of `patch`) and npm does it for you.

**Comment by mgol** [comment] 2016-03-08 20:12
For me it fails on the first category, `ajax`. Downgrading the `xmlrpc` module from `1.3.1` to `1.0.1` only changes the error from:
```
Running "wordpress-sync" task
Edited category ajax.
[1]    74915 segmentation fault  grunt --stack deploy
```
to:
```
Running "wordpress-sync" task
Edited category ajax.

<--- Last few GCs --->

   17066 ms: Scavenge 1399.6 (1457.5) -> 1399.6 (1457.5) MB, 3.8 / 0 ms (+ 8.9 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
   18104 ms: Mark-sweep 1399.6 (1457.5) -> 1399.4 (1455.5) MB, 1038.7 / 0 ms (+ 404.0 ms in 2852 steps since start of marking, biggest step 8.9 ms) [last resort gc].
   18901 ms: Mark-sweep 1399.4 (1455.5) -> 1398.7 (1457.5) MB, 797.1 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2f50f2fe3ac1 <JS Object>
    1: element [/Users/mgol/Documents/projects/public/jquery/api.jquery.com/node_modules/grunt-jquery-content/node_modules/wordpress/node_modules/xmlrpc/node_modules/xmlbuilder/lib/XMLFragment.js:~14] [pc=0x7ed13c44c62] (this=0xf7f398ea001 <an XMLFragment with map 0x2923d5836c99>,name=0x2f50f2f54c21 <String[5]: value>,attributes=0x2f50f2f04189 <undefined>,text=0x2f50f2f04189 <undefined>)
    2:...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
[1]    76484 abort      grunt --stack deploy
```

**Comment by mgol** [comment] 2016-03-08 20:52
I wanted to git bisect the api.jquery.com repo but I can't since on most commits even when I run `grunt deploy --force` I get:
```
Running "check-modules" task

Running "xmllint:all" (xmllint) task
Lint free files: 314

Running "clean-dist" task

Running "build-posts:page" (build-posts) task
Built 2 pages.

Running "build-resources:all" (build-resources) task
Built 64 resources.

Running "build-xml-entries:all" (build-xml-entries) task
>> Error: element a: validity error : ID after-function already defined
Warning: Task "build-xml-entries" failed. Used --force, continuing.

Running "build-xml-categories" task

Running "build-xml-full" task

Running "wordpress-validate" task
Warning: Mismatching versions for Gilded WordPress. Version 1.0.0 is installed as a Node.js module, but the WordPress server is running version 1.0.2. Used --force, continuing.

Running "wordpress-sync" task
Warning: Required task "wordpress-validate" failed. Used --force, continuing.

Done, but with warnings.
```

**Comment by AurelioDeRosa** [comment] 2016-03-09 23:26
Thank you for the reminder @mgol.

**Comment by feiwen8772** [comment] 2016-03-22 07:22
waiting

**Comment by dmethvin** [comment] 2016-03-22 12:38
It looks like we're still blocked on this. @scottgonzalez any thoughts on how to either fix or back out that breaking change?

**Comment by agcolom** [comment] 2016-03-22 13:35
just for the record, this is the error I'm getting: 
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Abort trap: 6

**Comment by agcolom** [comment] 2016-03-22 15:32
It seems the pb is caused by the sub categories. I noticed the process was hanging in method for mobile and this category has the path sub category. Removing this and the files that go in this sub category solves the pb.

**Comment by agcolom** [comment] 2016-03-22 21:28
Some updates: reverting jquery-wp-content back to 4.3.5 fixes it for me locally, but my guess is this is shared and we can't roll back just 2 sites?

**Comment by scottgonzalez** [comment] 2016-03-22 22:38
What version of WordPress are you using?

**Comment by agcolom** [comment] 2016-03-23 08:15
I am using WordPress 4.1-beta2-30788

**Comment by scottgonzalez** [comment] 2016-03-23 08:32
Well, that's why it works for you. You need to upgrade to at least 4.4.

**Comment by agcolom** [comment] 2016-03-23 08:44
I have upgraded to WordPress 4.5-beta4-37066 and it deploys fine locally.

**Comment by agcolom** [comment] 2016-03-23 08:59
With latest everything and WordPress 4.5-beta4-37066 it breaks when the path subcategory (first and only subcategory on this site) is being edited. I've added the output I get when running grunt deploy -v: 
[output.txt](https://github.com/jquery/api.jquery.com/files/185641/output.txt)

**Closed** 2016-03-31 13:29 UTC
