### ISSUE TITLE
Check on specific version documentation

### ISSUE THREAD

**Issue by pmourelle** [jquery/api.jquery.com#1140] opened 2019-08-01 15:28 UTC
Deprecated methods exist in documentation at same level as current ones. It's confusing and very easy to implement old methods based on current documentation structure/navigation.

Concrete example:
I just had to work on some jQuery related stuff after a while (a couple of years). So I checked the `live()` method args, got the thing and tried to make it work (using jQuery3). Obviously [now] it raised error. When I got in the docs again I found the tiny badge for "Deprecated" at the right, but if not for that the documentation for method has same hierarchy (as reachable through search and by URL pattern and everything, as a current not-deprecated method).

I think it may be in some different path structure like a `api.jquery.com/3.3/click` for example, so deprecated methods can't share same structure than latest version's.

It may be a feature more than an bug, but certainly is an issue.

**Comment by dmethvin** [comment] 2019-08-04 21:06
This is a duplicate of #971. If you would like to submit a PR updating the styling to clearly mark deprecated methods that would be great.

**Closed by dmethvin** 2019-08-04 21:06 UTC

**Comment by pmourelle** [comment] 2019-08-05 12:00
Hi @dmethvin, it's not only a visual/styling issue. Is how methods are shown or presented as results after being looked up from google (for example). URL for deprecated methods shouldn't have the same path as available methods, and exist behind some `/deprecated` or `/v2.x.y`.

**Comment by mgol** [comment] 2019-08-05 15:29
Why does URL have to be different?

**Comment by dmethvin** [comment] 2019-08-05 16:33
The xml does indicate when an API is deprecated so I'm not sure why the URL needs to encode that info as well. Plus it would break links unless we redirected.

**Comment by pmourelle** [comment] 2019-08-05 17:24
Having versioning structured by path is also easier to maintain/deploy (besides the ease of use for developers looking for specific methods on specific versions), like django docs for example: `https://docs.djangoproject.com/en/2.2/ref/middleware/#module-django.middleware.gzip`, it's easy to look for another version replacing just the bit of URL for it, or to follow a link and know just from the URL which version and method you're standing.

**Comment by mgol** [comment] 2019-08-05 17:41
It increases the maintenance burden, though, as now docs for older versions may also have inacurracies people will want to fix. We don't have a lot of people to manage all this so we're trying to reduce the burden.

jQuery doesn't undergo major API changes very often so the value from versioned docs would not be that big compared to other projects.

If pages for deprecated/removed APIs had big yellow banners warning about the deprecation/removal, would there still be any issue here?

**Comment by pmourelle** [comment] 2019-11-13 15:41
> It increases the maintenance burden, though, as now docs for older versions may also have inacurracies people will want to fix. We don't have a lot of people to manage all this so we're trying to reduce the burden.
I understand.

> If pages for deprecated/removed APIs had big yellow banners warning about the deprecation/removal, would there still be any issue here?
That could work.
