### ISSUE TITLE
Docs about prop vs attr is wrong regarding v. 1.9

### ISSUE THREAD

**Issue by teo1978** [jquery/api.jquery.com#359] opened 2013-08-21 19:58 UTC
According to: http://api.jquery.com/prop/

elem.checked	true (Boolean) Will change with checkbox state
$(elem).prop("checked")	true (Boolean) Will change with checkbox state
elem.getAttribute("checked")	"checked" (String) Initial state of the checkbox; does not change
$(elem).attr("checked") (1.6)	"checked" (String) Initial state of the checkbox; does not change
**$(elem).attr("checked") (1.6.1+)	"checked" (String) Will change with checkbox state**
$(elem).attr("checked") (pre-1.6)	true (Boolean) Changed with checkbox state

I haven't checked each and every version, but what I can certainly state is that the above is UNTRUE FOR VERSION 1.10

I think the table above is correct for versions <1.9, and untrue for version >=1.9, where attr("checked") will NOT change will checkbox state.

Compare to:
http://jquery.com/upgrade-guide/1.9/#attr-versus-prop-

**Comment by arthurvr** [comment] 2015-01-10 11:13
Duplicate of https://github.com/jquery/api.jquery.com/issues/288.

**Closed** 2015-01-10 11:23 UTC
Labels: help wanted
