### ISSUE TITLE
jQuery.ajax() JSONP links 404

### ISSUE THREAD

**Issue by modeckimellett** [jquery/api.jquery.com#1120] opened 2018-12-17 21:19 UTC
Hi everyone,

Currently there are 3 links to https://bob.ippoli.to/archives/2005/12/05/remote-json-jsonp/ which now 404s. The new url is https://bob.ippoli.to/javascript/mochikit/ajax/archives/2005/12/05/remote-json-jsonp or alternatively we can use a web archive link like https://web.archive.org/web/20170727011037/http://bob.ippoli.to/archives/2005/12/05/remote-json-jsonp/

The three links are in the datatype field in the parameters table (both with the text JSONP) and in the "datatypes" paragraph with the text "original post detailing its use".

If Mr. Ipplito sees this maybe he can add a 301 for us? @etrepum

Thanks!

**Comment by modeckimellett** [comment] 2018-12-17 21:19
I forgot to include the link to the offending page: https://api.jquery.com/jQuery.ajax/

**Comment by etrepum** [comment] 2018-12-17 22:14
I’ll take a look into why the permalink has broken when I get home later today. Must be some change in Jekyll and/or GitHub Pages as I haven’t touched it in some time.

**Comment by etrepum** [comment] 2018-12-18 00:15
Link should be fixed now.

**Comment by mgol** [comment] 2018-12-18 13:05
It seems the issue is resolved so I'll close it. Thank you!

**Closed by mgol** 2018-12-18 13:05 UTC
