### ISSUE TITLE
Document `html()` accepting DOM, jQuery object, etc.

### ISSUE THREAD

**Issue by brettz9** [jquery/api.jquery.com#1109] opened 2018-09-26 01:42 UTC
[`html()`](https://api.jquery.com/html/) ought to indicate that it also supports for its content argument, in addition to HTML strings (or function) the following: a DOM element, a text node, an array of elements and text nodes, or a jQuery object... (similar to how pages like `append` indicate their support for these).

This ability to replace all children is quite useful and not only when HTML strings are provided, but looking at the docs, I'd expect to be forced to use an HTML string or function...

Also, with the function argument, it should be documented that it too can return other types besides a string...

**Comment by dmethvin** [comment] 2018-09-26 23:19
You can see that the implementation for other stuff is basically `.empty().append(stuff)`, perhaps we could just document that in case it's not clear? I'm thinking something like this:

> The `.html()` method is not available in XML documents. To replace the content of an element in any document (HTML or XML) with content that is not an HTML string, use `.empty().append(content)` instead.

**Comment by brettz9** [comment] 2018-09-27 02:15
That sounds good, but being explicit about what can be allowed for `content` (DOM nodes, jQuery objects, arrays of nodes, etc.). There's nothing currently on the page for what `content` may be--the function signatures only use `htmlString` or `function`.

**Comment by brettz9** [comment] 2018-09-27 02:55
And I think it would also be helpful to distinguish if DOM and such passed to `html` gets stringified and passed to `innerHTML` or replaced via the DOM...

**Comment by ltlombardi** [comment] 2018-11-05 14:45
Went here to report the same issue. Typescript type definitions also should be updated. If possible, let them know of this error.

**Comment by mgol** [comment] 2018-11-05 15:02
Duplicate of issues #53, #152, #550 & #1101. See also PR #1049 where the rationale for not extending the accepted signatures has been laid out.

**Closed by mgol** 2018-11-05 15:02 UTC
