### ISSUE TITLE
"not well formatted" in Firefox

### ISSUE THREAD

**Issue by lpetrov** [jquery/api.jquery.com#822] opened 2015-10-29 16:35 UTC
Trying the example from: https://api.jquery.com/jQuery.parseXML/
Shows a warning in Firefox, saying "not well formatted".

Here is a demo of the same example from the docs:
http://jsfiddle.net/56g28hrs/

Its really weird, because the code is actually working properly, except the warning in Firefox (latest - 41.0.2 on Mac/OSX).
When the XML is parsed everything is just fine, except when the '$xml.find( "title" );' is executed, which triggers the warning.

So, is this a documentation problem OR an actual bug in jQuery when handling XML?

**Comment by agcolom** [comment] 2015-10-29 17:01
@lpetrov I am trying to reproduce but I am not getting the warning. Also on FF 41.0.2. but with  OS X 10.7.5. (could that be the difference?)

**Comment by lpetrov** [comment] 2015-10-29 20:24
I'm running OSX 10.10.5. But I don't see how this can be OS related.
Are you sure that the warnings are shown in the dev console?

<img width="1153" alt="screen shot 2015-10-29 at 10 23 02 pm" src="https://cloud.githubusercontent.com/assets/139877/10831017/addb5b98-7e8b-11e5-9963-6fa7705de515.png">

Thanks,
L

**Comment by agcolom** [comment] 2015-10-29 20:41
@lpetrov Ah yes, thanks for the screenshot. I can reproduce with your jsfiddle and logging warnings.

**Comment by agcolom** [comment] 2015-10-29 21:17
I'm wondering whether this is a duplicate of https://github.com/jquery/jquery/issues/2196 
cc:@gibson042

**Comment by gibson042** [comment] 2015-10-30 00:41
Confirmed. This is fixed in the 3.0.0 alpha: http://jsfiddle.net/56g28hrs/1/

**Closed by gibson042** 2015-10-30 00:41 UTC

**Comment by lpetrov** [comment] 2015-10-30 09:50
I can confirm that this is fixed in 3.0.

Thanks!
